"""Post drift score summaries as GitHub PR comments via the REST API."""

import os

COMMENT_MARKER = "<!-- driftlens-comment -->"


def _get_env(key: str) -> str | None:
    return os.environ.get(key)


def _pr_number() -> int | None:
    # GITHUB_REF for pull_request events: refs/pull/<number>/merge
    ref = _get_env("GITHUB_REF") or ""
    if ref.startswith("refs/pull/"):
        parts = ref.split("/")
        if len(parts) >= 3 and parts[2].isdigit():
            return int(parts[2])
    # Explicit override (useful for pull_request_target or manual)
    explicit = _get_env("GITHUB_PR_NUMBER")
    if explicit and explicit.isdigit():
        return int(explicit)
    return None


def _severity_badge(score: float, passed: bool) -> str:
    if passed:
        return "![pass](https://img.shields.io/badge/DriftLens-PASS-brightgreen)"
    if score <= 60:
        return "![warn](https://img.shields.io/badge/DriftLens-WARN-yellow)"
    return "![fail](https://img.shields.io/badge/DriftLens-FAIL-red)"


def format_comment(results: list[dict], overall: float, threshold: int, passed: bool) -> str:
    """Build the markdown comment body."""
    badge = _severity_badge(overall, passed)
    status = "PASS" if passed else "FAIL"
    lines = [
        COMMENT_MARKER,
        f"## DriftLens Drift Report {badge}",
        "",
        f"**Overall score:** `{overall:.1f} / 100` &nbsp;|&nbsp; "
        f"**Threshold:** `{threshold}` &nbsp;|&nbsp; **Result:** `{status}`",
        "",
        "| File | Verbosity | Structure | Complexity | Naming | Score |",
        "|------|-----------|-----------|------------|--------|-------|",
    ]
    for r in sorted(results, key=lambda x: -x["composite_score"]):
        lines.append(
            f"| `{r['filepath']}` "
            f"| {r['verbosity_delta']:+.3f} "
            f"| {r['structural_distance']:.3f} "
            f"| {r['complexity_gini_delta']:+.3f} "
            f"| {r['naming_violation_rate']:+.3f} "
            f"| **{r['composite_score']:.1f}** |"
        )
    lines.append("")
    lines.append("_Generated by [DriftLens](https://github.com/supashramesha/driftlens)_")
    return "\n".join(lines)


def post_pr_comment(results: list[dict], overall: float, threshold: int, passed: bool) -> None:
    """Post or update a PR comment with the drift summary.

    No-ops silently if required env vars are missing.
    """
    import requests  # lazy import — not available in all environments

    token = _get_env("GITHUB_TOKEN")
    repo = _get_env("GITHUB_REPOSITORY")
    pr = _pr_number()

    if not (token and repo and pr):
        return

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    base_url = f"https://api.github.com/repos/{repo}/issues/{pr}/comments"

    # Look for an existing DriftLens comment to update
    existing_id: int | None = None
    page = 1
    while True:
        resp = requests.get(base_url, headers=headers, params={"per_page": 100, "page": page}, timeout=15)
        resp.raise_for_status()
        comments = resp.json()
        if not comments:
            break
        for c in comments:
            if COMMENT_MARKER in c.get("body", ""):
                existing_id = c["id"]
                break
        if existing_id or len(comments) < 100:
            break
        page += 1

    body = format_comment(results, overall, threshold, passed)

    if existing_id:
        requests.patch(
            f"https://api.github.com/repos/{repo}/issues/comments/{existing_id}",
            headers=headers,
            json={"body": body},
            timeout=15,
        ).raise_for_status()
    else:
        requests.post(base_url, headers=headers, json={"body": body}, timeout=15).raise_for_status()
